import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navber from "./components/navber/Navber";
import AuthContext from "@/AuthContext/AuthContext";
import { ToastContainer } from "react-toastify";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="max-w-[90%] mx-auto">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthContext>
          <Navber />
          {children}
          <ToastContainer />
        </AuthContext>
      </body>
    </html>
  );
}
